import type { Metadata } from "next";
import { Montserrat, Playfair_Display } from 'next/font/google'
import { Great_Vibes, Lexend, Cormorant_Garamond, Cinzel } from "next/font/google";
import "./globals.css";

const greatVibes = Great_Vibes({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-greatvibes",
});

const lexend = Lexend({
  subsets: ['latin'],
  variable: "--font-lexend",
})

const cormorantgaramond = Cormorant_Garamond({
  subsets: ["latin"],
  variable: "--font-cormorantgaramond"
})

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

const cinzel = Cinzel({
  subsets: ['latin'],
  variable: "--font-cinzel",
})

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
})

export const metadata: Metadata = {
  title: "Danny Tailors",
  icons: "/logo.svg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${playfair.variable} ${greatVibes.variable} ${lexend.variable} ${cormorantgaramond.variable} ${cinzel.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
